spring.application.name=mailnest
spring.datasource.url=jdbc:postgresql://localhost:5432/mailnest
spring.datasource.username=postgres
spring.datasource.password=postgres
app.base-url=http://localhost:8080

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level traceId=%X{traceId} spanId=%X{spanId} [%thread] %logger{36} - %msg%n

app.email.base-url=http://localhost:8081
app.email.sender=test@gmail.com
app.email.authorization-token=my-secret-token
app.email.timeout-millis=10000

app.hmac-secret=very-secret-key-change-this